@echo off
setlocal EnableExtensions EnableDelayedExpansion

set ROOT_DIR=%~dp0
cd /d "%ROOT_DIR%"

:: --- Configuration (Hardcoded) ---
set "JAVA_HOME=C:\Program Files\Java\jdk-11.0.12"
set "GRADLE_USER_HOME=D:/Android-Config/.gradle"
set "ADB_PATH=D:\Android-Sdk\sdk\platform-tools\adb.exe"
set "ANDROID_SDK_ROOT=D:\Android-Sdk\sdk"

:: --- App Configuration ---
set "PACKAGE_NAME=com.leo.myapplication"
set "MAIN_ACTIVITY=com.mg.sdk.demo.MainActivity"

echo [VERIFY] Environment Configured:
echo   JAVA_HOME=%JAVA_HOME%
echo   GRADLE_USER_HOME=%GRADLE_USER_HOME%
echo   ADB_PATH=%ADB_PATH%
echo   ANDROID_SDK_ROOT=%ANDROID_SDK_ROOT%

:: --- Auto-Generate local.properties for Portability ---
:: Escape backslashes for properties file
set "SDK_DIR_ESCAPED=%ANDROID_SDK_ROOT:\=\\%"
(
  echo ## This file is automatically generated by run_app_rtn.bat
  echo sdk.dir=%SDK_DIR_ESCAPED%
) > "local.properties"

echo [VERIFY] Step1: Gradle assembleDebug
call "%ROOT_DIR%gradlew.bat" :app:assembleDebug
if errorlevel 1 (
  echo [VERIFY] assembleDebug failed
  exit /b 101
)

set APK_PATH=%ROOT_DIR%app\build\outputs\apk\debug\app-debug.apk
if not exist "%APK_PATH%" (
  echo [VERIFY] APK not found: %APK_PATH%
  exit /b 102
)

:: --- Prepare ADB ---
set "ADB_EXEC=%ADB_PATH%"
if not exist "!ADB_EXEC!" (
     echo [VERIFY] Configured ADB_PATH not found: !ADB_EXEC!
     exit /b 0
)

for /f "tokens=1" %%i in ('"!ADB_EXEC!" get-state 2^>nul') do set ADB_STATE=%%i
if /i not "%ADB_STATE%"=="device" (
  echo [VERIFY] no device, skip install/launch
  exit /b 0
)

echo [VERIFY] Step2: adb install
"%ADB_EXEC%" install -r "%APK_PATH%"
if errorlevel 1 (
  echo [VERIFY] adb install failed
  exit /b 103
)

echo [VERIFY] Step3: adb launch
"%ADB_EXEC%" shell am start -n %PACKAGE_NAME%/%MAIN_ACTIVITY%
if errorlevel 1 (
  echo [VERIFY] adb launch failed
  exit /b 104
)

echo [VERIFY] OK
exit /b 0
