dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven{ url 'https://maven.aliyun.com/nexus/content/groups/public/' }
        //snapshot开发调试版本仓库
        maven{  name = "SonatypeSnapshots"
            url = "https://central.sonatype.com/repository/maven-snapshots/" }
        google()
        mavenCentral()
        
    }
}
rootProject.name = "GradleProject-20251024"
include ':app'
